[machine]
name="Machine 1"	#Name of the machine being monitored

[sensing]
current_range = 20	#nominal rating of the Current Clamp
# uncomment the adc that you are using (default is BCRobotics)
adc = "BCRobotics"
#adc = "Grove"
#adc = "Gravity"


