[machine]
name="Process_1"	#Name of the process being monitored

[sensing]
# uncomment the adc that you are using (default is MLX90614)
#adc = "W1ThermSensor"   # Always connect the DS18B20 sensor to GPIO4 or PIN 7 of the RPI4
#adc = "K-type"
#adc = "AHT20"
#adc = "MLX90614_temp"
adc = "SHT30"

[threshold]
t1 = "20"