#=-= Define Interface Modules =-=
[interface.mb1]
    module="modbus"
    class="ModbusTCPSync"
[interface.mb1.config]
    adapter_addr="192.168.0.7"
    adapter_port=502

#=-= Define Device Modules =-=
[device.mfm1]
    module="multi_function_meter_HOBUT"
    class="HOBUT_850_LTHN"
    interface="mb1"
[device.mfm1.config]
    slave_id=1
[device.mfm1.variables]
    I1 = "current_rms"

#=-= Define Calculation Modules =-=

#=-= Define Calculation Pipelines =-=
[pipelines]
    empty_pipeline = []

#=-= Define Measurements Pipelines =-=
[measurement]
    module="gen_sample"
    class="SingleSample"
[measurement.config]
    period = 1.0 # seconds
[[measurement.sensing_stacks]]
    device = "mfm1"
    pipeline = "empty_pipeline"
    constants = {'phase'='single'}
    
[output.single_phase]
    path = "power_monitoring/{{machine}}/{{phase}}"
[output.single_phase.spec]
    machine = "#Machine_1"
    timestamp = '$.timestamp'
    current = "$.current_rms"
    phase = "$.phase"

[mqtt]
    broker = "mqtt.docker.local"
    port = 1883   #common mqtt ports are 1883 and 8883
    base_topic_template = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds
